export * from './amortizacionHistorico.service';
import { AmortizacionHistoricoService } from './amortizacionHistorico.service';
export * from './appParameter.service';
import { AppParameterService } from './appParameter.service';
export * from './bidone.service';
import { BidoneService } from './bidone.service';
export * from './categoria.service';
import { CategoriaService } from './categoria.service';
export * from './categoriasLang.service';
import { CategoriasLangService } from './categoriasLang.service';
export * from './center.service';
import { CenterService } from './center.service';
export * from './centmachine.service';
import { CentmachineService } from './centmachine.service';
export * from './centrosCoste.service';
import { CentrosCosteService } from './centrosCoste.service';
export * from './centrosView.service';
import { CentrosViewService } from './centrosView.service';
export * from './chasi.service';
import { ChasiService } from './chasi.service';
export * from './chasisHistorico.service';
import { ChasisHistoricoService } from './chasisHistorico.service';
export * from './combustible.service';
import { CombustibleService } from './combustible.service';
export * from './deposit.service';
import { DepositService } from './deposit.service';
export * from './deposito.service';
import { DepositoService } from './deposito.service';
export * from './detail.service';
import { DetailService } from './detail.service';
export * from './element.service';
import { ElementService } from './element.service';
export * from './empresa.service';
import { EmpresaService } from './empresa.service';
export * from './empresasView.service';
import { EmpresasViewService } from './empresasView.service';
export * from './equipos.service';
import { EquiposService } from './equipos.service';
export * from './familia.service';
import { FamiliaService } from './familia.service';
export * from './familiasLang.service';
import { FamiliasLangService } from './familiasLang.service';
export * from './family.service';
import { FamilyService } from './family.service';
export * from './financieroHistorico.service';
import { FinancieroHistoricoService } from './financieroHistorico.service';
export * from './financieroHistoricosbck.service';
import { FinancieroHistoricosbckService } from './financieroHistoricosbck.service';
export * from './garage.service';
import { GarageService } from './garage.service';
export * from './gastosTaller.service';
import { GastosTallerService } from './gastosTaller.service';
export * from './gastosTallerDoc.service';
import { GastosTallerDocService } from './gastosTallerDoc.service';
export * from './globalTablesValuesView.service';
import { GlobalTablesValuesViewService } from './globalTablesValuesView.service';
export * from './gnc.service';
import { GncService } from './gnc.service';
export * from './gncsDoc.service';
import { GncsDocService } from './gncsDoc.service';
export * from './gncsHistorico.service';
import { GncsHistoricoService } from './gncsHistorico.service';
export * from './grua.service';
import { GruaService } from './grua.service';
export * from './gruasDoc.service';
import { GruasDocService } from './gruasDoc.service';
export * from './gruasHistorico.service';
import { GruasHistoricoService } from './gruasHistorico.service';
export * from './gruposCentro.service';
import { GruposCentroService } from './gruposCentro.service';
export * from './gruposCentrosView.service';
import { GruposCentrosViewService } from './gruposCentrosView.service';
export * from './hmKm.service';
import { HmKmService } from './hmKm.service';
export * from './hmKmHistorico.service';
import { HmKmHistoricoService } from './hmKmHistorico.service';
export * from './hmKmHistoricosBck.service';
import { HmKmHistoricosBckService } from './hmKmHistoricosBck.service';
export * from './implemento.service';
import { ImplementoService } from './implemento.service';
export * from './implementosHistorico.service';
import { ImplementosHistoricoService } from './implementosHistorico.service';
export * from './impuesto.service';
import { ImpuestoService } from './impuesto.service';
export * from './impuestosHistorico.service';
import { ImpuestosHistoricoService } from './impuestosHistorico.service';
export * from './inspeccionesTecnica.service';
import { InspeccionesTecnicaService } from './inspeccionesTecnica.service';
export * from './inspeccionesTecnicasDoc.service';
import { InspeccionesTecnicasDocService } from './inspeccionesTecnicasDoc.service';
export * from './inspeccionesTecnicasHistorico.service';
import { InspeccionesTecnicasHistoricoService } from './inspeccionesTecnicasHistorico.service';
export * from './instalacione.service';
import { InstalacioneService } from './instalacione.service';
export * from './instalacionesElemento.service';
import { InstalacionesElementoService } from './instalacionesElemento.service';
export * from './instalacionesOperacione.service';
import { InstalacionesOperacioneService } from './instalacionesOperacione.service';
export * from './instalacionesOperacionesLang.service';
import { InstalacionesOperacionesLangService } from './instalacionesOperacionesLang.service';
export * from './installation.service';
import { InstallationService } from './installation.service';
export * from './level.service';
import { LevelService } from './level.service';
export * from './liter.service';
import { LiterService } from './liter.service';
export * from './machine.service';
import { MachineService } from './machine.service';
export * from './maintenance.service';
import { MaintenanceService } from './maintenance.service';
export * from './mantenimientoRepostaje.service';
import { MantenimientoRepostajeService } from './mantenimientoRepostaje.service';
export * from './maquinaria.service';
import { MaquinariaService } from './maquinaria.service';
export * from './maquinariaCentrosHistorico.service';
import { MaquinariaCentrosHistoricoService } from './maquinariaCentrosHistorico.service';
export * from './maquinariaDoc.service';
import { MaquinariaDocService } from './maquinariaDoc.service';
export * from './maquinariaDocView.service';
import { MaquinariaDocViewService } from './maquinariaDocView.service';
export * from './maquinariaImagenesDoc.service';
import { MaquinariaImagenesDocService } from './maquinariaImagenesDoc.service';
export * from './maquinariaView.service';
import { MaquinariaViewService } from './maquinariaView.service';
export * from './maquinariasEliminada.service';
import { MaquinariasEliminadaService } from './maquinariasEliminada.service';
export * from './maquinariasFechaExpedicion.service';
import { MaquinariasFechaExpedicionService } from './maquinariasFechaExpedicion.service';
export * from './maquinariasGnc.service';
import { MaquinariasGncService } from './maquinariasGnc.service';
export * from './maquinariasHistorico.service';
import { MaquinariasHistoricoService } from './maquinariasHistorico.service';
export * from './maquinariasNivele.service';
import { MaquinariasNiveleService } from './maquinariasNivele.service';
export * from './maquinariasNivelesDoc.service';
import { MaquinariasNivelesDocService } from './maquinariasNivelesDoc.service';
export * from './marca.service';
import { MarcaService } from './marca.service';
export * from './marcasReferenciasMateriale.service';
import { MarcasReferenciasMaterialeService } from './marcasReferenciasMateriale.service';
export * from './moneda.service';
import { MonedaService } from './moneda.service';
export * from './nivelesMantenimiento.service';
import { NivelesMantenimientoService } from './nivelesMantenimiento.service';
export * from './nivelesMantenimientoAccione.service';
import { NivelesMantenimientoAccioneService } from './nivelesMantenimientoAccione.service';
export * from './nivelesMantenimientoAccionesLang.service';
import { NivelesMantenimientoAccionesLangService } from './nivelesMantenimientoAccionesLang.service';
export * from './nivelesMantenimientoGruposAccione.service';
import { NivelesMantenimientoGruposAccioneService } from './nivelesMantenimientoGruposAccione.service';
export * from './nivelesMantenimientoTipos.service';
import { NivelesMantenimientoTiposService } from './nivelesMantenimientoTipos.service';
export * from './nivelesMantenimientoTiposAccione.service';
import { NivelesMantenimientoTiposAccioneService } from './nivelesMantenimientoTiposAccione.service';
export * from './notificacionesEstadoMaquinariaExterno.service';
import { NotificacionesEstadoMaquinariaExternoService } from './notificacionesEstadoMaquinariaExterno.service';
export * from './observacione.service';
import { ObservacioneService } from './observacione.service';
export * from './observation.service';
import { ObservationService } from './observation.service';
export * from './operation.service';
import { OperationService } from './operation.service';
export * from './parametro.service';
import { ParametroService } from './parametro.service';
export * from './parteTrabajoDoc.service';
import { ParteTrabajoDocService } from './parteTrabajoDoc.service';
export * from './parteTrabajoMateriale.service';
import { ParteTrabajoMaterialeService } from './parteTrabajoMateriale.service';
export * from './parteTrabajoMecanico.service';
import { ParteTrabajoMecanicoService } from './parteTrabajoMecanico.service';
export * from './partesTrabajo.service';
import { PartesTrabajoService } from './partesTrabajo.service';
export * from './partesTrabajoDoc.service';
import { PartesTrabajoDocService } from './partesTrabajoDoc.service';
export * from './pbiTasasView.service';
import { PbiTasasViewService } from './pbiTasasView.service';
export * from './pesoCarga.service';
import { PesoCargaService } from './pesoCarga.service';
export * from './prestamosStock.service';
import { PrestamosStockService } from './prestamosStock.service';
export * from './proveedore.service';
import { ProveedoreService } from './proveedore.service';
export * from './proximosMantenimiento.service';
import { ProximosMantenimientoService } from './proximosMantenimiento.service';
export * from './proximosMantenimientosHora.service';
import { ProximosMantenimientosHoraService } from './proximosMantenimientosHora.service';
export * from './ratiosView.service';
import { RatiosViewService } from './ratiosView.service';
export * from './referenciasMateriale.service';
import { ReferenciasMaterialeService } from './referenciasMateriale.service';
export * from './regional.service';
import { RegionalService } from './regional.service';
export * from './regularizacionesStock.service';
import { RegularizacionesStockService } from './regularizacionesStock.service';
export * from './repair.service';
import { RepairService } from './repair.service';
export * from './reparacione.service';
import { ReparacioneService } from './reparacione.service';
export * from './reparacionesAdjuntosDoc.service';
import { ReparacionesAdjuntosDocService } from './reparacionesAdjuntosDoc.service';
export * from './reparacionesCentroView.service';
import { ReparacionesCentroViewService } from './reparacionesCentroView.service';
export * from './reparacionesDoc.service';
import { ReparacionesDocService } from './reparacionesDoc.service';
export * from './reparacionesHistorico.service';
import { ReparacionesHistoricoService } from './reparacionesHistorico.service';
export * from './repostaje.service';
import { RepostajeService } from './repostaje.service';
export * from './rlsPbiControlAcceso.service';
import { RlsPbiControlAccesoService } from './rlsPbiControlAcceso.service';
export * from './seguro.service';
import { SeguroService } from './seguro.service';
export * from './seguro1.service';
import { Seguro1Service } from './seguro1.service';
export * from './segurosDoc.service';
import { SegurosDocService } from './segurosDoc.service';
export * from './segurosHistorico.service';
import { SegurosHistoricoService } from './segurosHistorico.service';
export * from './sequence.service';
import { SequenceService } from './sequence.service';
export * from './solred.service';
import { SolredService } from './solred.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './subFamilia.service';
import { SubFamiliaService } from './subFamilia.service';
export * from './subFamiliasLang.service';
import { SubFamiliasLangService } from './subFamiliasLang.service';
export * from './subFamiliasNivele.service';
import { SubFamiliasNiveleService } from './subFamiliasNivele.service';
export * from './subFamiliasReferenciasMateriale.service';
import { SubFamiliasReferenciasMaterialeService } from './subFamiliasReferenciasMateriale.service';
export * from './supply.service';
import { SupplyService } from './supply.service';
export * from './tacografo.service';
import { TacografoService } from './tacografo.service';
export * from './tacografosDoc.service';
import { TacografosDocService } from './tacografosDoc.service';
export * from './tacografosHistorico.service';
import { TacografosHistoricoService } from './tacografosHistorico.service';
export * from './tasasCentrosView.service';
import { TasasCentrosViewService } from './tasasCentrosView.service';
export * from './tasasHistorico.service';
import { TasasHistoricoService } from './tasasHistorico.service';
export * from './tasasHistorico1.service';
import { TasasHistorico1Service } from './tasasHistorico1.service';
export * from './tasasView.service';
import { TasasViewService } from './tasasView.service';
export * from './type.service';
import { TypeService } from './type.service';
export * from './unidadMedidaTiposCombustible.service';
import { UnidadMedidaTiposCombustibleService } from './unidadMedidaTiposCombustible.service';
export * from './unidadesMedida.service';
import { UnidadesMedidaService } from './unidadesMedida.service';
export * from './unidadesMedidaLang.service';
import { UnidadesMedidaLangService } from './unidadesMedidaLang.service';
export * from './userTasksView.service';
import { UserTasksViewService } from './userTasksView.service';
export * from './weight.service';
import { WeightService } from './weight.service';
export * from './workingmaintenance.service';
import { WorkingmaintenanceService } from './workingmaintenance.service';
export * from './workingpart.service';
import { WorkingpartService } from './workingpart.service';
export * from './xCentrosCoste.service';
import { XCentrosCosteService } from './xCentrosCoste.service';
export * from './xEmpresa.service';
import { XEmpresaService } from './xEmpresa.service';
export * from './xGlobalTable.service';
import { XGlobalTableService } from './xGlobalTable.service';
export * from './xGlobalTablesValue.service';
import { XGlobalTablesValueService } from './xGlobalTablesValue.service';
export * from './xGlobalTablesValuesLang.service';
import { XGlobalTablesValuesLangService } from './xGlobalTablesValuesLang.service';
export * from './xGruposCentro.service';
import { XGruposCentroService } from './xGruposCentro.service';
export const APIS = [AmortizacionHistoricoService, AppParameterService, BidoneService, CategoriaService, CategoriasLangService, CenterService, CentmachineService, CentrosCosteService, CentrosViewService, ChasiService, ChasisHistoricoService, CombustibleService, DepositService, DepositoService, DetailService, ElementService, EmpresaService, EmpresasViewService, EquiposService, FamiliaService, FamiliasLangService, FamilyService, FinancieroHistoricoService, FinancieroHistoricosbckService, GarageService, GastosTallerService, GastosTallerDocService, GlobalTablesValuesViewService, GncService, GncsDocService, GncsHistoricoService, GruaService, GruasDocService, GruasHistoricoService, GruposCentroService, GruposCentrosViewService, HmKmService, HmKmHistoricoService, HmKmHistoricosBckService, ImplementoService, ImplementosHistoricoService, ImpuestoService, ImpuestosHistoricoService, InspeccionesTecnicaService, InspeccionesTecnicasDocService, InspeccionesTecnicasHistoricoService, InstalacioneService, InstalacionesElementoService, InstalacionesOperacioneService, InstalacionesOperacionesLangService, InstallationService, LevelService, LiterService, MachineService, MaintenanceService, MantenimientoRepostajeService, MaquinariaService, MaquinariaCentrosHistoricoService, MaquinariaDocService, MaquinariaDocViewService, MaquinariaImagenesDocService, MaquinariaViewService, MaquinariasEliminadaService, MaquinariasFechaExpedicionService, MaquinariasGncService, MaquinariasHistoricoService, MaquinariasNiveleService, MaquinariasNivelesDocService, MarcaService, MarcasReferenciasMaterialeService, MonedaService, NivelesMantenimientoService, NivelesMantenimientoAccioneService, NivelesMantenimientoAccionesLangService, NivelesMantenimientoGruposAccioneService, NivelesMantenimientoTiposService, NivelesMantenimientoTiposAccioneService, NotificacionesEstadoMaquinariaExternoService, ObservacioneService, ObservationService, OperationService, ParametroService, ParteTrabajoDocService, ParteTrabajoMaterialeService, ParteTrabajoMecanicoService, PartesTrabajoService, PartesTrabajoDocService, PbiTasasViewService, PesoCargaService, PrestamosStockService, ProveedoreService, ProximosMantenimientoService, ProximosMantenimientosHoraService, RatiosViewService, ReferenciasMaterialeService, RegionalService, RegularizacionesStockService, RepairService, ReparacioneService, ReparacionesAdjuntosDocService, ReparacionesCentroViewService, ReparacionesDocService, ReparacionesHistoricoService, RepostajeService, RlsPbiControlAccesoService, SeguroService, Seguro1Service, SegurosDocService, SegurosHistoricoService, SequenceService, SolredService, StockService, SubFamiliaService, SubFamiliasLangService, SubFamiliasNiveleService, SubFamiliasReferenciasMaterialeService, SupplyService, TacografoService, TacografosDocService, TacografosHistoricoService, TasasCentrosViewService, TasasHistoricoService, TasasHistorico1Service, TasasViewService, TypeService, UnidadMedidaTiposCombustibleService, UnidadesMedidaService, UnidadesMedidaLangService, UserTasksViewService, WeightService, WorkingmaintenanceService, WorkingpartService, XCentrosCosteService, XEmpresaService, XGlobalTableService, XGlobalTablesValueService, XGlobalTablesValuesLangService, XGruposCentroService];
