export * from './categoria.service';
import { CategoriaService } from './categoria.service';
export * from './categoriasLang.service';
import { CategoriasLangService } from './categoriasLang.service';
export * from './chasisHistorico.service';
import { ChasisHistoricoService } from './chasisHistorico.service';
export * from './deposito.service';
import { DepositoService } from './deposito.service';
export * from './equipos.service';
import { EquiposService } from './equipos.service';
export * from './familia.service';
import { FamiliaService } from './familia.service';
export * from './familiasLang.service';
import { FamiliasLangService } from './familiasLang.service';
export * from './financieroHistorico.service';
import { FinancieroHistoricoService } from './financieroHistorico.service';
export * from './financieroHistoricosbck.service';
import { FinancieroHistoricosbckService } from './financieroHistoricosbck.service';
export * from './gastosTaller.service';
import { GastosTallerService } from './gastosTaller.service';
export * from './gastosTallerDoc.service';
import { GastosTallerDocService } from './gastosTallerDoc.service';
export * from './gnc.service';
import { GncService } from './gnc.service';
export * from './gncsDoc.service';
import { GncsDocService } from './gncsDoc.service';
export * from './gncsHistorico.service';
import { GncsHistoricoService } from './gncsHistorico.service';
export * from './grua.service';
import { GruaService } from './grua.service';
export * from './gruasDoc.service';
import { GruasDocService } from './gruasDoc.service';
export * from './gruasHistorico.service';
import { GruasHistoricoService } from './gruasHistorico.service';
export * from './hmKm.service';
import { HmKmService } from './hmKm.service';
export * from './hmKmHistorico.service';
import { HmKmHistoricoService } from './hmKmHistorico.service';
export * from './hmKmHistoricosBck.service';
import { HmKmHistoricosBckService } from './hmKmHistoricosBck.service';
export * from './implemento.service';
import { ImplementoService } from './implemento.service';
export * from './implementosHistorico.service';
import { ImplementosHistoricoService } from './implementosHistorico.service';
export * from './impuesto.service';
import { ImpuestoService } from './impuesto.service';
export * from './impuestosHistorico.service';
import { ImpuestosHistoricoService } from './impuestosHistorico.service';
export * from './inspeccionesTecnica.service';
import { InspeccionesTecnicaService } from './inspeccionesTecnica.service';
export * from './inspeccionesTecnicasDoc.service';
import { InspeccionesTecnicasDocService } from './inspeccionesTecnicasDoc.service';
export * from './inspeccionesTecnicasHistorico.service';
import { InspeccionesTecnicasHistoricoService } from './inspeccionesTecnicasHistorico.service';
export * from './instalacione.service';
import { InstalacioneService } from './instalacione.service';
export * from './instalacionesElemento.service';
import { InstalacionesElementoService } from './instalacionesElemento.service';
export * from './instalacionesOperacione.service';
import { InstalacionesOperacioneService } from './instalacionesOperacione.service';
export * from './instalacionesOperacionesLang.service';
import { InstalacionesOperacionesLangService } from './instalacionesOperacionesLang.service';
export * from './mantenimientoRepostaje.service';
import { MantenimientoRepostajeService } from './mantenimientoRepostaje.service';
export * from './maquinaria.service';
import { MaquinariaService } from './maquinaria.service';
export * from './maquinariaCentrosHistorico.service';
import { MaquinariaCentrosHistoricoService } from './maquinariaCentrosHistorico.service';
export * from './maquinariaDoc.service';
import { MaquinariaDocService } from './maquinariaDoc.service';
export * from './maquinariaImagenesDoc.service';
import { MaquinariaImagenesDocService } from './maquinariaImagenesDoc.service';
export * from './maquinariasEliminada.service';
import { MaquinariasEliminadaService } from './maquinariasEliminada.service';
export * from './maquinariasHistorico.service';
import { MaquinariasHistoricoService } from './maquinariasHistorico.service';
export * from './maquinariasNivele.service';
import { MaquinariasNiveleService } from './maquinariasNivele.service';
export * from './maquinariasNivelesDoc.service';
import { MaquinariasNivelesDocService } from './maquinariasNivelesDoc.service';
export * from './marca.service';
import { MarcaService } from './marca.service';
export * from './marcasReferenciasMateriale.service';
import { MarcasReferenciasMaterialeService } from './marcasReferenciasMateriale.service';
export * from './nivelesMantenimiento.service';
import { NivelesMantenimientoService } from './nivelesMantenimiento.service';
export * from './nivelesMantenimientoAccione.service';
import { NivelesMantenimientoAccioneService } from './nivelesMantenimientoAccione.service';
export * from './nivelesMantenimientoAccionesLang.service';
import { NivelesMantenimientoAccionesLangService } from './nivelesMantenimientoAccionesLang.service';
export * from './nivelesMantenimientoGruposAccione.service';
import { NivelesMantenimientoGruposAccioneService } from './nivelesMantenimientoGruposAccione.service';
export * from './nivelesMantenimientoTipos.service';
import { NivelesMantenimientoTiposService } from './nivelesMantenimientoTipos.service';
export * from './nivelesMantenimientoTiposAccione.service';
import { NivelesMantenimientoTiposAccioneService } from './nivelesMantenimientoTiposAccione.service';
export * from './notificacionesEstadoMaquinariaExterno.service';
import { NotificacionesEstadoMaquinariaExternoService } from './notificacionesEstadoMaquinariaExterno.service';
export * from './observacione.service';
import { ObservacioneService } from './observacione.service';
export * from './parteTrabajoDoc.service';
import { ParteTrabajoDocService } from './parteTrabajoDoc.service';
export * from './parteTrabajoMateriale.service';
import { ParteTrabajoMaterialeService } from './parteTrabajoMateriale.service';
export * from './parteTrabajoMecanico.service';
import { ParteTrabajoMecanicoService } from './parteTrabajoMecanico.service';
export * from './partesTrabajo.service';
import { PartesTrabajoService } from './partesTrabajo.service';
export * from './partesTrabajoDoc.service';
import { PartesTrabajoDocService } from './partesTrabajoDoc.service';
export * from './pesoCarga.service';
import { PesoCargaService } from './pesoCarga.service';
export * from './prestamosStock.service';
import { PrestamosStockService } from './prestamosStock.service';
export * from './proveedore.service';
import { ProveedoreService } from './proveedore.service';
export * from './referenciasMateriale.service';
import { ReferenciasMaterialeService } from './referenciasMateriale.service';
export * from './regularizacionesStock.service';
import { RegularizacionesStockService } from './regularizacionesStock.service';
export * from './reparacione.service';
import { ReparacioneService } from './reparacione.service';
export * from './reparacionesAdjuntosDoc.service';
import { ReparacionesAdjuntosDocService } from './reparacionesAdjuntosDoc.service';
export * from './reparacionesDoc.service';
import { ReparacionesDocService } from './reparacionesDoc.service';
export * from './reparacionesHistorico.service';
import { ReparacionesHistoricoService } from './reparacionesHistorico.service';
export * from './repostaje.service';
import { RepostajeService } from './repostaje.service';
export * from './seguro.service';
import { SeguroService } from './seguro.service';
export * from './segurosDoc.service';
import { SegurosDocService } from './segurosDoc.service';
export * from './segurosHistorico.service';
import { SegurosHistoricoService } from './segurosHistorico.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './subFamilia.service';
import { SubFamiliaService } from './subFamilia.service';
export * from './subFamiliasLang.service';
import { SubFamiliasLangService } from './subFamiliasLang.service';
export * from './subFamiliasNivele.service';
import { SubFamiliasNiveleService } from './subFamiliasNivele.service';
export * from './subFamiliasReferenciasMateriale.service';
import { SubFamiliasReferenciasMaterialeService } from './subFamiliasReferenciasMateriale.service';
export * from './tacografo.service';
import { TacografoService } from './tacografo.service';
export * from './tacografosDoc.service';
import { TacografosDocService } from './tacografosDoc.service';
export * from './tacografosHistorico.service';
import { TacografosHistoricoService } from './tacografosHistorico.service';
export * from './tasasHistorico.service';
import { TasasHistoricoService } from './tasasHistorico.service';
export * from './unidadMedidaTiposCombustible.service';
import { UnidadMedidaTiposCombustibleService } from './unidadMedidaTiposCombustible.service';
export * from './unidadesMedida.service';
import { UnidadesMedidaService } from './unidadesMedida.service';
export * from './unidadesMedidaLang.service';
import { UnidadesMedidaLangService } from './unidadesMedidaLang.service';
export * from './xCentrosCoste.service';
import { XCentrosCosteService } from './xCentrosCoste.service';
export * from './xEmpresa.service';
import { XEmpresaService } from './xEmpresa.service';
export * from './xGlobalTable.service';
import { XGlobalTableService } from './xGlobalTable.service';
export * from './xGlobalTablesValue.service';
import { XGlobalTablesValueService } from './xGlobalTablesValue.service';
export * from './xGlobalTablesValuesLang.service';
import { XGlobalTablesValuesLangService } from './xGlobalTablesValuesLang.service';
export * from './xGruposCentro.service';
import { XGruposCentroService } from './xGruposCentro.service';
export const APIS = [CategoriaService, CategoriasLangService, ChasisHistoricoService, DepositoService, EquiposService, FamiliaService, FamiliasLangService, FinancieroHistoricoService, FinancieroHistoricosbckService, GastosTallerService, GastosTallerDocService, GncService, GncsDocService, GncsHistoricoService, GruaService, GruasDocService, GruasHistoricoService, HmKmService, HmKmHistoricoService, HmKmHistoricosBckService, ImplementoService, ImplementosHistoricoService, ImpuestoService, ImpuestosHistoricoService, InspeccionesTecnicaService, InspeccionesTecnicasDocService, InspeccionesTecnicasHistoricoService, InstalacioneService, InstalacionesElementoService, InstalacionesOperacioneService, InstalacionesOperacionesLangService, MantenimientoRepostajeService, MaquinariaService, MaquinariaCentrosHistoricoService, MaquinariaDocService, MaquinariaImagenesDocService, MaquinariasEliminadaService, MaquinariasHistoricoService, MaquinariasNiveleService, MaquinariasNivelesDocService, MarcaService, MarcasReferenciasMaterialeService, NivelesMantenimientoService, NivelesMantenimientoAccioneService, NivelesMantenimientoAccionesLangService, NivelesMantenimientoGruposAccioneService, NivelesMantenimientoTiposService, NivelesMantenimientoTiposAccioneService, NotificacionesEstadoMaquinariaExternoService, ObservacioneService, ParteTrabajoDocService, ParteTrabajoMaterialeService, ParteTrabajoMecanicoService, PartesTrabajoService, PartesTrabajoDocService, PesoCargaService, PrestamosStockService, ProveedoreService, ReferenciasMaterialeService, RegularizacionesStockService, ReparacioneService, ReparacionesAdjuntosDocService, ReparacionesDocService, ReparacionesHistoricoService, RepostajeService, SeguroService, SegurosDocService, SegurosHistoricoService, StockService, SubFamiliaService, SubFamiliasLangService, SubFamiliasNiveleService, SubFamiliasReferenciasMaterialeService, TacografoService, TacografosDocService, TacografosHistoricoService, TasasHistoricoService, UnidadMedidaTiposCombustibleService, UnidadesMedidaService, UnidadesMedidaLangService, XCentrosCosteService, XEmpresaService, XGlobalTableService, XGlobalTablesValueService, XGlobalTablesValuesLangService, XGruposCentroService];
