export * from './amortizacionHistorico.service';
import { AmortizacionHistoricoService } from './amortizacionHistorico.service';
export * from './appParameter.service';
import { AppParameterService } from './appParameter.service';
export * from './bidones.service';
import { BidonesService } from './bidones.service';
export * from './centrosCoste.service';
import { CentrosCosteService } from './centrosCoste.service';
export * from './depositos.service';
import { DepositosService } from './depositos.service';
export * from './familias.service';
import { FamiliasService } from './familias.service';
export * from './gastosTaller.service';
import { GastosTallerService } from './gastosTaller.service';
export * from './gnc.service';
import { GncService } from './gnc.service';
export * from './gncDocs.service';
import { GncDocsService } from './gncDocs.service';
export * from './gruas.service';
import { GruasService } from './gruas.service';
export * from './gruposCentro.service';
import { GruposCentroService } from './gruposCentro.service';
export * from './hmKmHistorico.service';
import { HmKmHistoricoService } from './hmKmHistorico.service';
export * from './impuestos.service';
import { ImpuestosService } from './impuestos.service';
export * from './impuestosHistorico.service';
import { ImpuestosHistoricoService } from './impuestosHistorico.service';
export * from './inspeccionesTecnicasHistorico.service';
import { InspeccionesTecnicasHistoricoService } from './inspeccionesTecnicasHistorico.service';
export * from './instalaciones.service';
import { InstalacionesService } from './instalaciones.service';
export * from './maquinarias.service';
import { MaquinariasService } from './maquinarias.service';
export * from './maquinariasChasis.service';
import { MaquinariasChasisService } from './maquinariasChasis.service';
export * from './maquinariasDocs.service';
import { MaquinariasDocsService } from './maquinariasDocs.service';
export * from './maquinariasEquipos.service';
import { MaquinariasEquiposService } from './maquinariasEquipos.service';
export * from './maquinariasHistorico.service';
import { MaquinariasHistoricoService } from './maquinariasHistorico.service';
export * from './maquinariasImagenesDocs.service';
import { MaquinariasImagenesDocsService } from './maquinariasImagenesDocs.service';
export * from './maquinariasImplementos.service';
import { MaquinariasImplementosService } from './maquinariasImplementos.service';
export * from './maquinariasInspeccionesTecnicas.service';
import { MaquinariasInspeccionesTecnicasService } from './maquinariasInspeccionesTecnicas.service';
export * from './maquinariasInspeccionesTecnicasDocs.service';
import { MaquinariasInspeccionesTecnicasDocsService } from './maquinariasInspeccionesTecnicasDocs.service';
export * from './maquinariasNiveles.service';
import { MaquinariasNivelesService } from './maquinariasNiveles.service';
export * from './maquinariasNivelesDocs.service';
import { MaquinariasNivelesDocsService } from './maquinariasNivelesDocs.service';
export * from './maquinariasObservaciones.service';
import { MaquinariasObservacionesService } from './maquinariasObservaciones.service';
export * from './maquinariasReparaciones.service';
import { MaquinariasReparacionesService } from './maquinariasReparaciones.service';
export * from './maquinariasRepostajes.service';
import { MaquinariasRepostajesService } from './maquinariasRepostajes.service';
export * from './maquinariasTacografos.service';
import { MaquinariasTacografosService } from './maquinariasTacografos.service';
export * from './marca.service';
import { MarcaService } from './marca.service';
export * from './nivelMantenimiento.service';
import { NivelMantenimientoService } from './nivelMantenimiento.service';
export * from './nivelMantenimientoAccion.service';
import { NivelMantenimientoAccionService } from './nivelMantenimientoAccion.service';
export * from './nivelMantenimientoAccionesLang.service';
import { NivelMantenimientoAccionesLangService } from './nivelMantenimientoAccionesLang.service';
export * from './nivelMantenimientoTipo.service';
import { NivelMantenimientoTipoService } from './nivelMantenimientoTipo.service';
export * from './nivelMantenimientoTiposAccion.service';
import { NivelMantenimientoTiposAccionService } from './nivelMantenimientoTiposAccion.service';
export * from './parteTrabajo.service';
import { ParteTrabajoService } from './parteTrabajo.service';
export * from './parteTrabajoDoc.service';
import { ParteTrabajoDocService } from './parteTrabajoDoc.service';
export * from './parteTrabajoMecanico.service';
import { ParteTrabajoMecanicoService } from './parteTrabajoMecanico.service';
export * from './partesTrabajoDoc.service';
import { PartesTrabajoDocService } from './partesTrabajoDoc.service';
export * from './pesoCarga.service';
import { PesoCargaService } from './pesoCarga.service';
export * from './prestamosStock.service';
import { PrestamosStockService } from './prestamosStock.service';
export * from './proveedor.service';
import { ProveedorService } from './proveedor.service';
export * from './reparacionesDoc.service';
import { ReparacionesDocService } from './reparacionesDoc.service';
export * from './seguro.service';
import { SeguroService } from './seguro.service';
export * from './segurosDoc.service';
import { SegurosDocService } from './segurosDoc.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './tacografosDoc.service';
import { TacografosDocService } from './tacografosDoc.service';
export * from './tacografosHistorico.service';
import { TacografosHistoricoService } from './tacografosHistorico.service';
export * from './unidadMedidaTiposCombustible.service';
import { UnidadMedidaTiposCombustibleService } from './unidadMedidaTiposCombustible.service';
export * from './unidadesMedida.service';
import { UnidadesMedidaService } from './unidadesMedida.service';
export * from './unidadesMedidaLang.service';
import { UnidadesMedidaLangService } from './unidadesMedidaLang.service';
export * from './vistas.service';
import { VistasService } from './vistas.service';
export * from './xGlobalTable.service';
import { XGlobalTableService } from './xGlobalTable.service';
export * from './xGlobalTablesValue.service';
import { XGlobalTablesValueService } from './xGlobalTablesValue.service';
export * from './xGlobalTablesValuesLang.service';
import { XGlobalTablesValuesLangService } from './xGlobalTablesValuesLang.service';
export const APIS = [AmortizacionHistoricoService, AppParameterService, BidonesService, CentrosCosteService, DepositosService, FamiliasService, GastosTallerService, GncService, GncDocsService, GruasService, GruposCentroService, HmKmHistoricoService, ImpuestosService, ImpuestosHistoricoService, InspeccionesTecnicasHistoricoService, InstalacionesService, MaquinariasService, MaquinariasChasisService, MaquinariasDocsService, MaquinariasEquiposService, MaquinariasHistoricoService, MaquinariasImagenesDocsService, MaquinariasImplementosService, MaquinariasInspeccionesTecnicasService, MaquinariasInspeccionesTecnicasDocsService, MaquinariasNivelesService, MaquinariasNivelesDocsService, MaquinariasObservacionesService, MaquinariasReparacionesService, MaquinariasRepostajesService, MaquinariasTacografosService, MarcaService, NivelMantenimientoService, NivelMantenimientoAccionService, NivelMantenimientoAccionesLangService, NivelMantenimientoTipoService, NivelMantenimientoTiposAccionService, ParteTrabajoService, ParteTrabajoDocService, ParteTrabajoMecanicoService, PartesTrabajoDocService, PesoCargaService, PrestamosStockService, ProveedorService, ReparacionesDocService, SeguroService, SegurosDocService, StockService, TacografosDocService, TacografosHistoricoService, UnidadMedidaTiposCombustibleService, UnidadesMedidaService, UnidadesMedidaLangService, VistasService, XGlobalTableService, XGlobalTablesValueService, XGlobalTablesValuesLangService];
