/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateNivelesMantenimientoAccionesLangDto } from '../model/createNivelesMantenimientoAccionesLangDto';
import { NivelesMantenimientoAccionesLangDto } from '../model/nivelesMantenimientoAccionesLangDto';
import { NivelesMantenimientoAccionesLangDtoPaginatedResult } from '../model/nivelesMantenimientoAccionesLangDtoPaginatedResult';
import { NivelesMantenimientoAccionesLangDtoResult } from '../model/nivelesMantenimientoAccionesLangDtoResult';
import { UpdateNivelesMantenimientoAccionesLangDto } from '../model/updateNivelesMantenimientoAccionesLangDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class NivelesMantenimientoAccionesLangService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2NivelesMantenimientoAccionesLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<NivelesMantenimientoAccionesLangDtoPaginatedResult>;
    public apiV2NivelesMantenimientoAccionesLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NivelesMantenimientoAccionesLangDtoPaginatedResult>>;
    public apiV2NivelesMantenimientoAccionesLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NivelesMantenimientoAccionesLangDtoPaginatedResult>>;
    public apiV2NivelesMantenimientoAccionesLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            queryParameters = queryParameters.set('Filters', <any>filters);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<NivelesMantenimientoAccionesLangDtoPaginatedResult>('get',`${this.basePath}/api/v2/nivelesMantenimientoAccionesLang`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2NivelesMantenimientoAccionesLangIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiV2NivelesMantenimientoAccionesLangIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiV2NivelesMantenimientoAccionesLangIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiV2NivelesMantenimientoAccionesLangIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2NivelesMantenimientoAccionesLangIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/v2/nivelesMantenimientoAccionesLang/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2NivelesMantenimientoAccionesLangIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<NivelesMantenimientoAccionesLangDto>;
    public apiV2NivelesMantenimientoAccionesLangIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NivelesMantenimientoAccionesLangDto>>;
    public apiV2NivelesMantenimientoAccionesLangIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NivelesMantenimientoAccionesLangDto>>;
    public apiV2NivelesMantenimientoAccionesLangIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2NivelesMantenimientoAccionesLangIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<NivelesMantenimientoAccionesLangDto>('get',`${this.basePath}/api/v2/nivelesMantenimientoAccionesLang/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2NivelesMantenimientoAccionesLangPost(body?: CreateNivelesMantenimientoAccionesLangDto, observe?: 'body', reportProgress?: boolean): Observable<NivelesMantenimientoAccionesLangDtoResult>;
    public apiV2NivelesMantenimientoAccionesLangPost(body?: CreateNivelesMantenimientoAccionesLangDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NivelesMantenimientoAccionesLangDtoResult>>;
    public apiV2NivelesMantenimientoAccionesLangPost(body?: CreateNivelesMantenimientoAccionesLangDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NivelesMantenimientoAccionesLangDtoResult>>;
    public apiV2NivelesMantenimientoAccionesLangPost(body?: CreateNivelesMantenimientoAccionesLangDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<NivelesMantenimientoAccionesLangDtoResult>('post',`${this.basePath}/api/v2/nivelesMantenimientoAccionesLang`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2NivelesMantenimientoAccionesLangPut(body?: UpdateNivelesMantenimientoAccionesLangDto, observe?: 'body', reportProgress?: boolean): Observable<NivelesMantenimientoAccionesLangDtoResult>;
    public apiV2NivelesMantenimientoAccionesLangPut(body?: UpdateNivelesMantenimientoAccionesLangDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NivelesMantenimientoAccionesLangDtoResult>>;
    public apiV2NivelesMantenimientoAccionesLangPut(body?: UpdateNivelesMantenimientoAccionesLangDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NivelesMantenimientoAccionesLangDtoResult>>;
    public apiV2NivelesMantenimientoAccionesLangPut(body?: UpdateNivelesMantenimientoAccionesLangDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<NivelesMantenimientoAccionesLangDtoResult>('put',`${this.basePath}/api/v2/nivelesMantenimientoAccionesLang`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
