/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateSeguro1Dto { 
    costeAnio?: number;
    costePrecio?: number;
    categoriaSeguro?: number;
    tipoSeguro?: string;
    numPoliza: string;
    inicioPoliza?: Date;
    finPoliza?: Date;
    aseguradora: string;
    matricula?: string;
    centerId?: string;
    nombre?: string;
    regionalId?: number;
    generalId?: string;
    moneda: string;
}