/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCosteDto } from './centrosCosteDto';
import { EmpresaDto } from './empresaDto';
import { FamiliaDto } from './familiaDto';
import { ImpuestoDto } from './impuestoDto';
import { SeguroDto } from './seguroDto';
import { SubFamiliaDto } from './subFamiliaDto';

export interface MaquinariaDto { 
    id?: number;
    idEmpresa?: number;
    empresa?: EmpresaDto;
    idCentro?: number;
    centroCoste?: CentrosCosteDto;
    idCentroCompra?: number;
    centroCompra?: CentrosCosteDto;
    idFamilia?: number;
    familia?: FamiliaDto;
    idSubfamilia?: number;
    subfamilia?: SubFamiliaDto;
    idSeguro?: number;
    seguro?: SeguroDto;
    idImpuesto?: number;
    impuesto?: ImpuestoDto;
    matricula?: string;
    fechaMatriculacion?: Date;
    bastidor?: string;
    codTipoCombustible?: string;
    codNivelEmisiones?: string;
    codEstadoMaquinaria?: string;
    fechaGnc?: Date;
    codMoneda?: string;
    conductor?: string;
    servicio?: string;
    mediaHorasDia?: number;
    mediaKmsDia?: number;
    operativa?: boolean;
    disposicion?: boolean;
    comentarios?: string;
    fechaTasas?: Date;
    duracionTasas?: number;
    avisoTracking?: boolean;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    esImplemento?: boolean;
}