/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCoste } from './centrosCoste';
import { Empresa } from './empresa';
import { Familia } from './familia';
import { Impuesto } from './impuesto';
import { Seguro } from './seguro';
import { SubFamilia } from './subFamilia';

export interface Maquinaria { 
    id?: number;
    idEmpresa?: number;
    empresa?: Empresa;
    idCentro?: number;
    centroCoste?: CentrosCoste;
    idCentroCompra?: number;
    centroCompra?: CentrosCoste;
    idFamilia?: number;
    familia?: Familia;
    idSubfamilia?: number;
    subfamilia?: SubFamilia;
    idSeguro?: number;
    seguro?: Seguro;
    idImpuesto?: number;
    impuesto?: Impuesto;
    matricula?: string;
    fechaMatriculacion?: string;
    bastidor?: string;
    codTipoCombustible?: string;
    codNivelEmisiones?: string;
    codEstadoMaquinaria?: string;
    fechaGnc?: string;
    codMoneda?: string;
    conductor?: string;
    servicio?: string;
    mediaHorasDia?: number;
    mediaKmsDia?: number;
    operativa?: boolean;
    disposicion?: boolean;
    comentarios?: string;
    fechaTasas?: Date;
    duracionTasas?: number;
    avisoTracking?: boolean;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    esImplemento?: boolean;
}