/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PartesTrabajoDto } from './partesTrabajoDto';
import { ReferenciasMaterialeDto } from './referenciasMaterialeDto';

export interface ParteTrabajoMaterialeDto { 
    id?: number;
    idParteTrabajo?: number;
    parteTrabajo?: PartesTrabajoDto;
    idReferenciaMaterial?: number;
    referenciaMaterial?: ReferenciasMaterialeDto;
    descripcion: string;
    cantidad?: number;
    gastoConmutable?: boolean;
    createdBy: string;
    createdAt?: Date;
    changedBy: string;
    changedAt?: Date;
}