/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCosteDto } from './centrosCosteDto';
import { EmpresaDto } from './empresaDto';

export interface PrestamosStockDto { 
    id?: number;
    idEmpresa?: number;
    empresa?: EmpresaDto;
    idCentroOrigen?: number;
    centroOrigen?: CentrosCosteDto;
    idCentroDestino?: number;
    centroDestino?: CentrosCosteDto;
    idReferenciaMaterial?: number;
    codMoneda?: string;
    cantidad?: number;
    valor?: number;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}