/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmpresaDto } from './empresaDto';

export interface ProveedoreDto { 
    id?: number;
    idEmpresa?: number;
    empresa?: EmpresaDto;
    docIdentificacion: string;
    nombre: string;
    direccion?: string;
    telefono?: string;
    comentarios?: string;
    sap?: string;
    createdBy: string;
    createdAt?: Date;
    changedBy: string;
    changedAt?: Date;
}