/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmpresaDto } from './empresaDto';

export interface SeguroDto { 
    id?: number;
    codigo: string;
    idEmpresa?: number;
    empresa?: EmpresaDto;
    aseguradora: string;
    fechaInicio?: Date;
    fechaFin?: Date;
    importe?: number;
    codMoneda: string;
    comentario?: string;
    codTipoSeguro?: string;
    codEstadoSeguro?: string;
    idMaquinaria?: number;
    createdBy: string;
    createdAt?: Date;
    changedBy: string;
    changedAt?: Date;
}