/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Empresa } from './empresa';
import { Familia } from './familia';
import { NivelesMantenimiento } from './nivelesMantenimiento';

export interface SubFamilia { 
    id?: number;
    idEmpresa?: number;
    empresa?: Empresa;
    idFamilia?: number;
    familia?: Familia;
    grua?: boolean;
    fichaTecnica?: boolean;
    inspeccionTecnica?: boolean;
    permisoCirculacion?: boolean;
    seguro?: boolean;
    tarjetaTransporte?: boolean;
    tacografo?: boolean;
    marcadoCe?: boolean;
    conformidad?: boolean;
    peso?: boolean;
    gnc?: boolean;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    idNivelMantenimientoChasis?: number;
    nivelMantenimientoChasis?: NivelesMantenimiento;
    idNivelMantenimientoEquipo?: number;
    nivelMantenimientoEquipo?: NivelesMantenimiento;
    idNivelMantenimientoImplemento?: number;
    nivelMantenimientoImplemento?: NivelesMantenimiento;
    esImplemento?: boolean;
}