/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReferenciasMaterialeDto } from './referenciasMaterialeDto';
import { SubFamiliaDto } from './subFamiliaDto';

export interface SubFamiliasReferenciasMaterialeDto { 
    id?: number;
    idSubFamilia?: number;
    subFamilia?: SubFamiliaDto;
    idReferenciaMaterial?: number;
    referenciaMaterial?: ReferenciasMaterialeDto;
    createdBy: string;
    createdAt?: Date;
    changedBy: string;
    changedAt?: Date;
}