/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmpresaDto } from './empresaDto';
import { NivelesMantenimientoDto } from './nivelesMantenimientoDto';
import { SubFamiliaDto } from './subFamiliaDto';

export interface SubFamiliasNiveleDto { 
    id?: number;
    idEmpresa?: number;
    empresa?: EmpresaDto;
    idSubfamilia?: number;
    subFamilia?: SubFamiliaDto;
    idNivelMantenimiento?: number;
    nivelMantenimiento?: NivelesMantenimientoDto;
}