/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TacografoDto } from './tacografoDto';

export interface TacografosDocDto { 
    id?: number;
    idTacografo?: number;
    tacografo?: TacografoDto;
    claveGuid?: string;
    extension: string;
    documento: string;
    nombre: string;
}