/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateRatiosViewDto { 
    id?: number;
    idMaquinaria?: number;
    centro: string;
    descripcion: string;
    matricula: string;
    nombreCentro: string;
    idGrupoCentro?: number;
    idGrupoCentroPadre?: number;
    fecha?: Date;
    reparaciones?: number;
    seguro?: number;
    impuesto?: number;
    inspecciones?: number;
    amortizaciones?: number;
    financieros?: number;
    tasa?: number;
    ratio?: number;
    moneda?: string;
    idCentro?: number;
}