/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateEmpresasViewDto { 
    id?: number;
    idNegocioRegionPais?: number;
    codigoRrhhsacyr?: string;
    codigo: string;
    nombre: string;
    tipoSociedad?: string;
    tipoConsolidacion?: string;
    documentoIdentificativo: string;
    codMoneda: string;
    contabilidad?: string;
    direccion?: string;
    codigoPostal?: string;
    telefono?: string;
    email?: string;
    ute?: boolean;
    codSap?: string;
    idPeople?: number;
    fecAlta?: Date;
    fecBaja?: Date;
    origen?: string;
}